"""create tables

Revision ID: bd7541cb7bac
Revises: 
Create Date: 2026-06-27 15:57:10.984067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7541cb7bac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор пользователя'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email адрес'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Имя пользователя'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Зашифрованный пароль'),
    sa.Column('role', sa.Enum('employer', 'applicant', name='user_roles'), nullable=False, comment='Роль пользователя'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор вакансии'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Идентификатор пользователя (работодателя)'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Название вакансии'),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание вакансии'),
    sa.Column('salary_from', sa.Numeric(precision=10, scale=2), nullable=True, comment='Зарплата от'),
    sa.Column('salary_to', sa.Numeric(precision=10, scale=2), nullable=True, comment='Зарплата до'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли вакансия'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор отклика'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Идентификатор пользователя (соискателя)'),
    sa.Column('job_id', sa.Integer(), nullable=False, comment='Идентификатор вакансии'),
    sa.Column('message', sa.Text(), nullable=True, comment='Сопроводительное письмо'),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='response_status'), nullable=False, comment='Статус отклика'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responses')
    op.drop_table('jobs')
    op.drop_table('users')
    # ### end Alembic commands ###
